spring:
  profiles.active: dev
server:
  port: 8080

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/db_pay?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 100
      min-idle: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      min-evictable-idle-time-millis: 1800000
  rabbitmq:
     host: localhost
     port: 5672
     username: guest
     password: guest